/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dao.CarroEstacionadoDao;
import dao.CarrosDao;
import dao.VagasDao;
import java.util.ArrayList;
import regrasDeNegocio.CarroEstacionado;
import regrasDeNegocio.Carros;
import regrasDeNegocio.Vagas;

/**
 *
 * @author rreei
 */
public class FormEstacionar extends javax.swing.JDialog {

    CarrosDao carroDao = new CarrosDao();
    VagasDao vagaDao = new VagasDao();
    CarroEstacionadoDao ce = new CarroEstacionadoDao();
    ArrayList<Vagas> listaVagas = new ArrayList();
    ArrayList<Carros> listaCarros = new ArrayList();

    /**
     * Creates new form FormEstacionar
     */
    public FormEstacionar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        CarregarComboBoxVaga();
        CarregarComboBoxCarro();
        CarregarListaDeCarros();
        CarregarListaDeVagas();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboVaga = new javax.swing.JComboBox<>();
        ComboCarro = new javax.swing.JComboBox<>();
        btEstacionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ComboVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboVagaActionPerformed(evt);
            }
        });

        btEstacionar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btEstacionar.setText("Estacionar");
        btEstacionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEstacionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(ComboVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(btEstacionar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboVaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(btEstacionar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboVagaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboVagaActionPerformed

    private void btEstacionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEstacionarActionPerformed
        // TODO add your handling code here:
        CarroEstacionado carroEst = new CarroEstacionado();
        int idCarro;
        int idVaga;
        int posicaoListaVaga;
        int posicaoListaCarro;
        posicaoListaVaga=ComboVaga.getSelectedIndex();
        posicaoListaCarro=ComboCarro.getSelectedIndex();
        idVaga = listaVagas.get(posicaoListaVaga).getIdVaga();
        idCarro =  listaCarros.get(posicaoListaCarro).getIdcarro();
        carroEst.setDataEntrada("01/01/1900");
        //carroEst.setIdCarro(idCarro);
        carroEst.setIdCarro(idCarro);
        //carroEst.setIdVaga(idVaga);
        carroEst.setIdVaga(idVaga);
        ce.cadastrarCarros(carroEst);
    }//GEN-LAST:event_btEstacionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEstacionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEstacionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEstacionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEstacionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormEstacionar dialog = new FormEstacionar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void CarregarComboBoxVaga() {
        ComboVaga.removeAllItems();
        vagaDao.carregarDados();
        vagaDao.proximo();
        do {
            ComboVaga.addItem(vagaDao.getVaga().getNumeroStr());
        } while (vagaDao.proximo());
    }

    public void CarregarComboBoxCarro() {
        ComboCarro.removeAll();
        carroDao.carregarDados();
        carroDao.proximo();

        do {
            ComboCarro.addItem(carroDao.getCarro().getPlaca());
        } while (carroDao.proximo());
    }

    public void CarregarListaDeVagas() {
        listaVagas.removeAll(listaVagas);
        vagaDao.carregarDados();
        vagaDao.proximo();
        do {
            listaVagas.add(vagaDao.getVaga());
        } while (vagaDao.proximo());

    }

    public void CarregarListaDeCarros() {
        listaCarros.removeAll(listaCarros);
        carroDao.carregarDados();
        carroDao.proximo();
        do {
            listaCarros.add(carroDao.getCarro());
        } while (carroDao.proximo());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboCarro;
    private javax.swing.JComboBox<String> ComboVaga;
    private javax.swing.JButton btEstacionar;
    // End of variables declaration//GEN-END:variables
}
